### ISSUE TITLE
Crash: FileAlreadyExistsException when saving same note to same folder

### ISSUE THREAD

**Issue by tuancoltech** [ARK-Builders/ARK-Memo#26]
Crash: `FileAlreadyExistsException` when saving same note to same folder.

```
java.nio.file.FileAlreadyExistsException: /storage/emulated/0/test1/10-1217600887.note
                                                                                                    	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:429)
                                                                                                    	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
                                                                                                    	at java.nio.file.Files.move(Files.java:1395)
                                                                                                    	at dev.arkbuilders.arkmemo.data.repositories.TextNotesRepoImpl.renameResourceWithNewResourceMeta(TextNotesRepoImpl.kt:115)
                                                                                                    	at dev.arkbuilders.arkmemo.data.repositories.TextNotesRepoImpl.access$renameResourceWithNewResourceMeta(TextNotesRepoImpl.kt:27)
                                                                                                    	at dev.arkbuilders.arkmemo.data.repositories.TextNotesRepoImpl$write$2.invokeSuspend(TextNotesRepoImpl.kt:91)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@59337dc, Dispatchers.IO]
```

**Comment by tuancoltech** [comment]
Fixed with this PR: https://github.com/ARK-Builders/ARK-Memo/pull/29
Closing now.
